### ISSUE TITLE
Deprecation warning since 2.1.3

### ISSUE THREAD

**Issue by ff2248** [khiav223577/active_model_cachers#39]
## Steps to reproduce

Upgrade to 2.1.3 and open rails console.

## Expected behavior

No deprecation warning

## Actual behavior

Got deprecation warning:
```
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.

You can opt into the new behavior and remove this warning by setting:

  config.active_record.raise_in_transactional_callbacks = true
```

## System configuration

**Rails version**: 4.2.10
**Ruby version**: 2.3.3

**Comment by khiav223577** [comment]
This is a warning from rails to inform us that `after_commit` behavior will be changed in Rails 5. See https://github.com/rails/rails/pull/14488. 

You could also find a similar issue here: https://github.com/carrierwaveuploader/carrierwave/issues/2082
