### ISSUE TITLE
can use newer request store?

### ISSUE THREAD

**Issue by saiqulhaq** [khiav223577/active_model_cachers#55]
https://github.com/khiav223577/active_model_cachers/blob/64bcb434474a4c832ce20831ba0cbbf0c7422760/active_model_cachers.gemspec#L42

is it possible to use  request_store (>= 1.5.0) ?

**Comment by khiav223577** [comment]
It looks safe to upgrade it from 1.4.1 to 1.5.0.
https://github.com/steveklabnik/request_store/compare/v1.4.1...v1.5.0

I am happy to upgrade the dependency and release a new version as soon as possible :)

**Comment by khiav223577** [comment]
Just release v2.1.8. See the [changelog](https://github.com/khiav223577/active_model_cachers/blob/master/CHANGELOG.md) for more details.
