### ISSUE TITLE
attribute cache is not being updated

### ISSUE THREAD

**Issue by saiqulhaq** [khiav223577/active_model_cachers#57]
let say I have following model

```
Class User < ApplicationRecord
end
```
with 1 attribute: `birthday`

then I added `cache_at` like this

```
Class User < ApplicationRecord
  cache_at :age, -> { code }, expiry_by: 'User#birthday'
end
```

on the first call, it cached correctly method `age`
but when I updated. the value `User.last.update birthday: xxx`

`User.last.cacher.age` still show the old cached value

my question is, how to clean the cache automatically when birthday data is updated?

and another question, on this method:

```
  cache_at :age, -> {
    #call birthday 
    birthday.year # => will raise error, birthday is nil
   # but 
   self.birthday.year # works
  }, expiry_by: 'User#birthday'

```

**Comment by khiav223577** [comment]
The first question can be solved by changing 
`cache_at :age, -> { code }, expiry_by: 'User#birthday'` to 
`cache_at :age, ->(_id) { code }, expiry_by: 'User#birthday'`

The behavior is a little confusing. Hope that we can find a good way to make it more easier to understand.

The following is the details of the mechanism you may be interested in:
---

The logic behinds it is complex. 
First, when you call `user.cacher.age`
I know that you are using the `cacher` from the `user` instance. I can access the `id` and use it to cache the data for the instance. The cache key of it is `"active_model_cachers_User_at_age_#{user.id}"`

But when we are going to expire the cache, I don't known the data is cached in instance level or class level
For example, we may have 
`cache_at :age, -> { code }, expiry_by: 'User#birthday'` and 
`cache_at :teenager_count, -> { User.where('birthday between XX and YY').count }, expiry_by: 'User#birthday'`

The second one is cache in class level. The cache key of it is `active_model_cachers_User_at_teenager_count`

When a user's birthday is updated, I have to expire `"active_model_cachers_User_at_age_#{user.id}"` and `active_model_cachers_User_at_teenager_count`. But I have no idea if the cache key should contains `_#{user.id}` suffix or not.

In current implementation, I take the number the arguments of the lambda to determine whether the cache should contain id.
https://github.com/khiav223577/active_model_cachers/blob/16f38ec2a1acfa9376617eff18b305cc1b3dff37/lib/active_model_cachers/active_record/extension.rb#L33

It is implicit though, any better idea?

**Comment by khiav223577** [comment]
> and another question, on this method:
> 
> ```
>   cache_at :age, -> {
>     #call birthday 
>     birthday.year # => will raise error, birthday is nil
>    # but 
>    self.birthday.year # works
>   }, expiry_by: 'User#birthday'
> ```

Could you create an executable test case? See: https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case for more details.

I've tested it and found it worked fine with the following test cases:

```rb
begin
  require 'bundler/inline'
rescue LoadError => e
  warn 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '~> 5.2'
  gem 'active_model_cachers', '~> 2.1.8'
  gem 'sqlite3'
end

require 'rails'
require 'active_model_cachers'
require 'minitest/autorun'
require 'logger'

Rails.cache = ActiveSupport::Cache::MemoryStore.new(expires_in: 5.minutes)

ActiveModelCachers.config do |config|
  config.store = Rails.cache
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
# ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table 'users', force: :cascade do |t|
    t.date :birthday
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class User < ApplicationRecord
  cache_at :age, ->(_) {
    now = Time.now.utc.to_date
    now.year - birthday.year - ((now.month > birthday.month || (now.month == birthday.month && now.day >= birthday.day)) ? 0 : 1)
  }, expire_by: 'User#birthday'
end

class BugTest < Minitest::Test
  def setup
    User.create!(birthday: 10.years.ago - 3.days)
  end

  def test_expire
    assert_equal({}, cache_data)

    assert_equal 10, User.last.cacher.age
    assert_equal({ "active_model_cachers_User_at_age_#{User.last.id}" => 10 }, cache_data)

    User.last.update(birthday: 10.years.ago + 3.days)
    assert_equal({}, cache_data)

    assert_equal 9, User.last.cacher.age
    assert_equal({ "active_model_cachers_User_at_age_#{User.last.id}" => 9 }, cache_data)
  end

  private

  def cache_data
    Rails.cache.instance_variable_get(:@data).transform_values(&:value)
  end
end
```

**Comment by saiqulhaq** [comment]
many thanks for the explanation

I just tried assocation caching

```
class User
  has_many :rewards
  cache_at :foo, ->(id) { count_rewards_xxxx }, expire_by: :rewards
end
```

it caches data for the first time only
but doesn't work when I updated, created or deleted one of reward record (user `#destroy` method)
it still show the old one

**Comment by saiqulhaq** [comment]
> > and another question, on this method:
> > ```
> >   cache_at :age, -> {
> >     #call birthday 
> >     birthday.year # => will raise error, birthday is nil
> >    # but 
> >    self.birthday.year # works
> >   }, expiry_by: 'User#birthday'
> > ```
> 
> Could you create an executable test case? See: 

sorry for this one, seems bug on my end
