### ISSUE TITLE
How can I force a method in model to always be cached?

### ISSUE THREAD

**Issue by neohunter** [khiav223577/active_model_cachers#59]
Let's suppose i've this
```ruby
  cache_at :heavy_method
  def heavy_method
   # ...
 end
```

I want to use the cache version each time my application does `MyModel.first.heavy_method`. I understand the advantages of having to use `MyModel.first.cacher.heavy_method` but sometimes I just need to always use the cache version for a given attribute, and update across all the application would be so long task.

**Comment by khiav223577** [comment]
How about using `delegate`? For example:

```rb
cache_at :heavy_method, ->{ heavy_method_without_cache }
delegate :heavy_method, to: :cacher

def heavy_method_without_cache
  # ...
end
```
